title: Cambridge Chem&Bio
baseURL: https://biobridgechem.co.uk/
languageCode: en-GB
defaultContentLanguage: en
hasCJKLanguage: true
enableRobotsTXT: true
enableGitInfo: false
buildFuture: true
summaryLength: 30
paginate: 24
disableKinds: [taxonomy, term]
outputs:
  home: [HTML, RSS]
  section: [HTML, RSS]
  page: [HTML]
permalinks:
  authors: /author/:slug/
imaging:
  quality: 82
  resampleFilter: lanczos
  anchor: smart
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
sitemap:
  changeFreq: monthly
  priority: 0.5
